name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - "4.14.1"
        coq-repo-url:
          - "https://github.com/ku-sldg/coq.git"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup pre-deps
        run: sudo apt install libgtk-3-0 libgtk-3-dev libgtksourceview-3.0-common libgtksourceview-3.0-dev opam

      - name: Restore Cached Install
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.opam
            ~/coq
          key: ${{ runner.OS }}-${{ matrix.ocaml-compiler }}
      
      - run: opam init
      - run: opam install -y dune coq lablgtk3-sourceview3

# We only need to setup the coq library again if it didnt get pulled from cache properly
# TODO: Ultimately this should be dependent on if this repo changes, but not important for now
      - name: Checkout and build external library
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          cd ~
          eval $(opam env)
          git clone ${{ matrix.coq-repo-url }}
          cd coq
          git switch cakeml-extraction
          make world
      
      - name: Cache Installs
        id: cache-install
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.opam
            ~/coq
          key: ${{ runner.OS }}-${{ matrix.ocaml-compiler }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Build
        run: |
          export COQBIN=~/coq/_build/install/default/bin/
          echo "COQBIN is $COQBIN"
          cd ${{ github.workspace }}/src
          $COQBIN/coq_makefile -f _CoqProject -o MAKEPRIME
          make -f MAKEPRIME
