name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - "4.14.1"
        coq-repo-url:
          - "https://github.com/ku-sldg/coq.git"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup pre-deps
        run: sudo apt install libgtk-3-0 libgtk-3-dev libgtksourceview-3.0-common libgtksourceview-3.0-dev opam

      - name: Restore Cached Install
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.opam
            ~/coq
          key: ${{ runner.OS }}-${{ matrix.ocaml-compiler }}
      
      - run: opam init
      - run: opam install -y dune coq lablgtk3-sourceview3

      - name: Checkout and build external library
        run: |
          cd ~
          eval $(opam env)
          git clone ${{ matrix.coq-repo-url }}
          cd coq
          echo "DIRECTORY_PATH=$(pwd)" >> $ENV
          echo "Directory path is $DIRECTORY_PATH"
          pwd
          git switch cakeml-extraction
          make world
          cd ..
      
      - name: Cache Installs
        id: cache-install
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.opam
            ~/coq
          key: ${{ runner.OS }}-${{ matrix.ocaml-compiler }}

      - name: Setup Coq Bin Path
        run: export COQBIN=~/coq/_build/install/default/bin/

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Build
        run: |
          pwd
          echo $COQBIN
          export COQBINN=~/coq/_build/install/default/bin/
          echo $COQBINN
          cd ${{ github.workspace }}/src
          $COQBIN/coq_makefile -f _CoqProject -o MAKEPRIME
          make -f MAKEPRIME
