name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      
    runs-on: ubuntu-latest

    env:
      COQ_REPO_PATH: "ku-sldg/coq"
      OCAML_VERSION: "4.14.1"
      COQ_REPO_BRANCH: "cakeml-extraction"

    steps:
      - name: Setup pre-deps
        run: sudo apt install libgtk-3-0 libgtk-3-dev libgtksourceview-3.0-common libgtksourceview-3.0-dev opam

      - name: Get latest commit hash of Coq Repo
        id: get_commit_hash
        run: |
          response=$(curl -s "https://api.github.com/repos/$COQ_REPO_PATH/commits/$COQ_REPO_BRANCH")
          commit_hash=$(echo "$response" | jq -r '.sha')
          echo "COMMIT_HASH=$commit_hash" >> $GITHUB_ENV

      - name: Restore Cached Install
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.opam
            ~/coq
          key: ${{ runner.OS }}-$OCAML_VERSION-${{ env.COMMIT_HASH }}
      
      - run: opam init
      - run: opam install -y dune coq lablgtk3-sourceview3

# We only need to setup the coq library again if it didnt get pulled from cache properly
# TODO: Ultimately this should be dependent on if this repo changes, but not important for now
      - name: Checkout and build external library
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          cd ~
          eval $(opam env)
          git clone https://github.com/$COQ_REPO_PATH.git
          cd coq
          git switch $COQ_REPO_BRANCH
          make world
      
      - name: Cache Installs
        id: cache-install
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.opam
            ~/coq
          key: ${{ runner.OS }}-$OCAML_VERSION-${{ env.COMMIT_HASH }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Build
        run: |
          export COQBIN=~/coq/_build/install/default/bin/
          echo "COQBIN is $COQBIN"
          cd ${{ github.workspace }}/src
          $COQBIN/coq_makefile -f _CoqProject -o MAKEPRIME
          make -f MAKEPRIME
