name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - "4.14.1"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup pre-deps
        run: sudo apt install libgtk-3-0 libgtk-3-dev libgtksourceview-3.0-common libgtksourceview-3.0-dev

      - run: opam init
        
      - name: Restore Cached Install
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.opam
            ~/coq
          key: ${{ runner.OS }}-${{ matrix.ocaml-compiler }}
    
#      - name: Setup Ocaml ${{ matrix.ocaml-compiler }}
#        if: steps.cache-ocaml-restore.outputs.cache-hit != 'true'
#        uses: ocaml/setup-ocaml@v2
#        with:
#          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: opam install -y dune coq lablgtk3-sourceview3

# NONDOC_INSTALL_TARGETS:=coq-core.install coq-stdlib.install coqide-server.install coqide.install coq.install
      - name: Checkout and build external library
        run: |
          eval $(opam env)
          git clone https://github.com/ku-sldg/coq.git
          cd coq
          git switch cakeml-extraction
          make world
          cd ..
      
      - name: Cache Installs
        id: cache-install
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.opam
            ~/coq
          key: ${{ runner.OS }}-${{ matrix.ocaml-compiler }}

      - name: Setup Coq Bin Path
        run: export COQBIN=~/coq/_build/install/default/bin/

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Build
        run: |
          cd ~/copland-avm/src
          $COQBIN/coq_makefile -f _CoqProject -o MAKEPRIME
          make -f MAKEPRIME
